spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200105
    url: jdbc:mysql://localhost:3306/miaosha
    hikari:
      pool-name: DataHikariCP
      #最大连接数
      maximum-pool-size: 10
      #最小空闲连接数，就是即使没有访问也保持连接数据库
      minimum-idle: 5
      #空闲连接最大存货时长，毫秒，即30分钟，默认10分钟
      idle-timeout: 1800000
      #连接存活的最长时间
      max-lifetime: 1800000
      #连接超时时间。30秒
      connection-timeout: 30000
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
  #thymeleaf配置
  thymeleaf:
    #关闭缓存
    cache: false
  #redis配置

  redis:
    cluster:
      max-redirects: 6
      nodes: 122.51.174.149:6379,122.51.174.149:6380,122.51.174.149:6381,106.13.203.5:6379,106.13.203.5:6380,106.13.203.5:6381
    #超时时间
    timeout: 10000ms
    #服务器地址
#    host: 122.51.174.149
#    #服务器端口
#    port: 6379
    #数据库，总共16个
    database: 0
    #密码
    password: 200105
    #配置redis数据库连接池
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1，即不超时，ms单位
        max-wait: 10000
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5

#配置mybatis-plus
mybatis-plus:
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.example.miaosha.bean
  #配置mapper包位置
  mapper-locations:  classpath*:/mapper/*Mapper.xml

# Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.example.miaosha.mapper: debug
